# Site
title:              이황로의 블로그입니다.
bio:                '개발 내용을 주로 다루고 있습니다.'
description:        "개발 내용을 주로 다루고 있습니다."
# reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpeg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
# url:                https://taylantatli.github.io/Moon
url:                http://localhost:4000
# url:                https://hwangrolee.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   https-hwangrolee-github-io

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email: hwangro123@gmail.com
# twitter:            username
# facebook:           username
github-url:         hwangrolee
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          hwangro-lee-68082a185
#xing:              username
# instagram:          username
#lastfm:            username
#tumblr:            username
medium:            '@lhr0419'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
